name: Generate GitHub wiki from wiki folder

on:
  push:
    paths:
      - 'wiki/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Update wiki
    steps:
    - uses: OrlovM/Wiki-Action@v1
      with:
        path: 'markdown_blog'
        token: ${{ secrets.GITHUB_TOKEN }}
